--- #YAML:1.0
name: URI-Find-Rule
version: 0.5
license: perl
distribution_type: module
requires:
  Test::More: 0
  Text::Glob: 0
  URI: 0
  URI::Find: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  URI::Find::Rule:
    file: lib/URI/Find/Rule.pm
    version: 0.5
generated_by: Module::Build version 0.19
